### PR TITLE
Fix #6: Could not parse snippet file has tab indent

### LINKED ISSUE #6: Does not find my snippets (made with tabs)
Looks like there is problem parsing the snippet file 

The following works:

```
{
"My Snippet": {
"prefix": "mySnippet",
"body": ["test snippet"],
"description": "test"
}
}

```
The following doesnt work. (made with 1 tab per indentation).

```
{
	"My Snippet": {
		"prefix": "mySnippet",
		"body": ["test snippet"],
		"description": "test"
	}
}

```

### PR DESCRIPTION
**Pull request by thongdong7**
Fix #6

### CODE REVIEW

**Comment by rebornix** [comment]
The tab escaping is used to fix https://github.com/rebornix/vscode-project-snippet/issues/4 , I'm afraid the removal will break that again.

**Comment by thongdong7** [comment]
@rebornix Thanks for the link. I just update the PR to use JSON5 to parse the snippet instead of using the built-in JSON. I believe that VSCode use JSON5 to parse the snippets too.

One of benefits of JSON5 I like is that it allow users to put the comments inside the snippet. http://json5.org/

I plan to create another PR for the unit test later.

**Comment by rebornix** [comment]
@thongdong7 in VS Code we parse the JSON file ourselves :) But I like it, with JSON5 we don't need to worry about the format or escaping too much. 

With two or more test cases, we can merge this PR. Thanks!

**Comment by thongdong7** [comment]
* Added unit test for #4 and #6 .
* Add TravisCI

Do you want to have AppVeyor in this PR too?

**Comment by rebornix** [comment]
@thongdong7 thanks, you are so considerate, yes appvoyer is another good addition.

**Comment by rebornix** [comment]
@thongdong7 thanks for your great work, I really like it!

**Comment by rebornix** [comment]
@thongdong7 I'll publish it once marketplace is back online (it's down 5 minutes ago).

**Comment by thongdong7** [comment]
I updated to 0.5.0. It works now. Thanks for amazing plugin :)

**Pull request merged**
